/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.hazelcast.query.datamodel;


import io.github.crabzilla.hazelcast.query.datamodel.tables.HzProjections;
import io.github.crabzilla.hazelcast.query.datamodel.tables.records.HzProjectionsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HzProjectionsRecord> HZ_PROJECTIONS_PKEY = UniqueKeys0.HZ_PROJECTIONS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<HzProjectionsRecord> HZ_PROJECTIONS_PKEY = Internal.createUniqueKey(HzProjections.HZ_PROJECTIONS, "hz_projections_pkey", new TableField[] { HzProjections.HZ_PROJECTIONS.CONSUMERID }, true);
    }
}
