/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.hazelcast.query.datamodel;


import io.github.crabzilla.hazelcast.query.datamodel.tables.HzProjections;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.hz_projections</code>.
     */
    public static final HzProjections HZ_PROJECTIONS = HzProjections.HZ_PROJECTIONS;
}
