/*
 * This file is generated by jOOQ.
*/
package example1.datamodel;


import example1.datamodel.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in example1db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>example1db.aggregate_roots</code>.
     */
    public static final AggregateRoots AGGREGATE_ROOTS = example1.datamodel.tables.AggregateRoots.AGGREGATE_ROOTS;

    /**
     * The table <code>example1db.customer_summary</code>.
     */
    public static final CustomerSummary CUSTOMER_SUMMARY = example1.datamodel.tables.CustomerSummary.CUSTOMER_SUMMARY;

    /**
     * The table <code>example1db.events_projection_channels</code>.
     */
    public static final EventsProjectionChannels EVENTS_PROJECTION_CHANNELS = example1.datamodel.tables.EventsProjectionChannels.EVENTS_PROJECTION_CHANNELS;

    /**
     * The table <code>example1db.idempotency</code>.
     */
    public static final Idempotency IDEMPOTENCY = example1.datamodel.tables.Idempotency.IDEMPOTENCY;

    /**
     * The table <code>example1db.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = example1.datamodel.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>example1db.units_of_work</code>.
     */
    public static final UnitsOfWork UNITS_OF_WORK = example1.datamodel.tables.UnitsOfWork.UNITS_OF_WORK;
}
