language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.11.2

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose rm -f
  - docker-compose up -d

cache:
  directories:
  - "$HOME/.m2"

install:
#  - mvn clean install -DskipTests
#  - cd ./crabzilla-example1/crabzilla-example1-database
#  - mvn compile flyway:migrate
#  - cd ../..
  - docker ps
  - sleep 30
  - docker ps
#  - mvn clean verify -P all-tests
#  - mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)
