:sourcedir: src/main/java
:source-highlighter: highlightjs
:highlightjsdir: highlight
:highlightjs-theme: rainbow
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
:toclevels: 4

https://vertx.io[image:https://img.shields.io/badge/vert.x-4.1.5-purple.svg[Vertx]]
https://github.com/crabzilla/crabzilla/actions/workflows/blank.yml[image:https://github.com/crabzilla/crabzilla/actions/workflows/blank.yml/badge.svg[CI]]
https://codecov.io/gh/crabzilla/crabzilla[image:https://codecov.io/gh/crabzilla/crabzilla/branch/main/graph/badge.svg[codecov]]
https://frontend.code-inspector.com/public/project/24241/crabzilla/dashboard[image:https://www.code-inspector.com/project/24241/score/svg[image]]
https://frontend.code-inspector.com/public/project/24241/crabzilla/dashboard[image:https://www.code-inspector.com/project/24241/status/svg[image]]
https://jitpack.io/#io.github.crabzilla/crabzilla[image:https://jitpack.io/v/io.github.crabzilla/crabzilla.svg[Jitpack]]

== Objectives

. Allows writing your testable `CQRS/ES` model with minimal dependencies.
. Allows consistently handling your commands and save resulting events into `Postgres`.
. Allows projecting events to your read models.

== Premisses

* Using https://vertx.io/docs/vertx-pg-client/java/[Vertx] to implement a `non-blocking IO` event store.
* Idiomatic Kotlin: type safeness: pattern matching, honouring your constructors.
* Immutability: state transitions occurs after computing results of pure functions `(State, Event) -> State`).
* JSON serialization using Kotlin serialization (other implementations are welcome).
* Consistent by default: before handling a command, your state ID is pessimistically locked using https://www.postgresql.org/docs/14/explicit-locking.html#ADVISORY-LOCKS[Postgres Advisory Locks]
* `EventsProjectorVerticle` allows handling projections strait from database: no need to publish your events to Kafka in order to handle your read model projections.

== Example application

https://github.com/rodolfodpk/accounts2[https://github.com/rodolfodpk/accounts2]

== Status

Seems like is finally reaching stable :)

== More info

https://crabzilla.github.io/crabzilla/docs/index.html[Documentation]
