:sourcedir: src/main/java
:source-highlighter: highlightjs
:highlightjsdir: highlight
:highlightjs-theme: rainbow
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/java]
:toclevels: 4


https://www.oracle.com/java/[image:https://img.shields.io/badge/Java-11-purple.svg[Vertx]]
https://kotlinlang.org/[image:https://img.shields.io/badge/Kotlin-1.6.20-purple.svg[Vertx]]
https://vertx.io[image:https://img.shields.io/badge/vert.x-4.2.7-purple.svg[Vertx]]
https://github.com/crabzilla/crabzilla/actions/workflows/blank.yml[image:https://github.com/crabzilla/crabzilla/actions/workflows/blank.yml/badge.svg[CI]]
https://codecov.io/gh/crabzilla/crabzilla[image:https://codecov.io/gh/crabzilla/crabzilla/branch/main/graph/badge.svg[codecov]]
https://frontend.code-inspector.com/public/project/24241/crabzilla/dashboard[image:https://api.codiga.io/project/24241/score/svg[image]]
https://frontend.code-inspector.com/public/project/24241/crabzilla/dashboard[image:https://api.codiga.io/project/24241/status/svg[image]]
https://jitpack.io/#io.github.crabzilla/crabzilla[image:https://jitpack.io/v/io.github.crabzilla/crabzilla.svg[Jitpack]]

== Objectives

. Allows writing your testable `CQRS/ES` model with minimal dependencies.
. Allows consistently handling your commands and save resulting events into `Postgres`.
. Allows consistently and ordered projecting your events to your view models in Postgres.
. Allows consistently and ordered publishing your events to Vertx eventbus, so you can integrate with any message broker, database, cache, etc.

== Approach

* Using key https://vertx.io/docs/vertx-pg-client/java/[Vertx] features to implement a `non-blocking IO` command and query engine.
* Using key `Postgres` features: json, notification and advisory locks.
* Idiomatic Kotlin: type safeness: pattern matching, honouring your constructors.
* Immutability: state transitions occurs after computing results of pure functions `(State, Event) -> State`.

== Features

=== Domain model

Your domain can be tested in BDD way without any dependency to Vertx: only to `crabzilla-core`:

** given command, then assertion
** given events, when command, then assertion
** given commands or events in any order, then assertion

=== Command

Your commands are consistently handled:

** Before handling a command, your state ID is pessimistically locked using https://www.postgresql.org/docs/14/explicit-locking.html#ADVISORY-LOCKS[Postgres Advisory Locks]. This helps to increase consistency.
** After a successful command, your projector will be notified (even in another machine) by using https://www.postgresql.org/docs/current/sql-notify.html[Postgres notify]. This helps to reduce eventual consistency delay.
** You can optionally project to view model within the same database transaction. This helps set based validation.
** You can optionally handle commands against 2 instances of the same state type (for example, transferring $ from account1 to account2) within the same database transaction. This helps to use https://martinfowler.com/eaaCatalog/unitOfWork.html[UnitOfWork]

Your events are serialized to JSON and stored to `Postgres`

** Using https://kotlinlang.org/docs/serialization.html[Kotlin serialization]
** Using https://github.com/FasterXML/jackson-module-kotlin[Jackson Kotlin Module]

=== Projection

After handling your commands and appending the respective events, you can use any mechanism to publish our events: CDC, pooling, etc. But there are some interesting ways to do it in Crabzilla:

* Your events can be consistently and ordered projected to your view model in Postgres.
* Your events can be consistently and ordered published to Vertx EventBus. You must handle idempotency.
** Using request reply.
** Using blocking request reply.
** Using or just publishing to it.
* You can consume your events in plain https://vertx.io/docs/apidocs/io/vertx/core/json/JsonObject.html[JsonObject] objects or to leverage your Json implementation (https://kotlinlang.org/docs/serialization.html[Kotlin serialization] or https://github.com/FasterXML/jackson-module-kotlin[Jackson Kotlin Module]) to consume them statically.

== Example application (a work in progress)

https://github.com/crabzilla/accounts-quarkus

== Status

Seems like it's finally reaching stable status :)
