/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.jooq.example1.datamodel.tables.records;


import io.github.crabzilla.jooq.example1.datamodel.tables.CustomerSummary;
import io.github.crabzilla.jooq.example1.datamodel.tables.interfaces.ICustomerSummary;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerSummaryRecord extends UpdatableRecordImpl<CustomerSummaryRecord> implements VertxPojo, Record3<Integer, String, Boolean>, ICustomerSummary {

    private static final long serialVersionUID = -1218279837;

    /**
     * Setter for <code>public.customer_summary.id</code>.
     */
    @Override
    public CustomerSummaryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.customer_summary.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.customer_summary.name</code>.
     */
    @Override
    public CustomerSummaryRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.customer_summary.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customer_summary.is_active</code>.
     */
    @Override
    public CustomerSummaryRecord setIsActive(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.customer_summary.is_active</code>.
     */
    @Override
    public Boolean getIsActive() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CustomerSummary.CUSTOMER_SUMMARY.ID;
    }

    @Override
    public Field<String> field2() {
        return CustomerSummary.CUSTOMER_SUMMARY.NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return CustomerSummary.CUSTOMER_SUMMARY.IS_ACTIVE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Boolean component3() {
        return getIsActive();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Boolean value3() {
        return getIsActive();
    }

    @Override
    public CustomerSummaryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CustomerSummaryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public CustomerSummaryRecord value3(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public CustomerSummaryRecord values(Integer value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ICustomerSummary from) {
        setId(from.getId());
        setName(from.getName());
        setIsActive(from.getIsActive());
    }

    @Override
    public <E extends ICustomerSummary> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerSummaryRecord
     */
    public CustomerSummaryRecord() {
        super(CustomerSummary.CUSTOMER_SUMMARY);
    }

    /**
     * Create a detached, initialised CustomerSummaryRecord
     */
    public CustomerSummaryRecord(Integer id, String name, Boolean isActive) {
        super(CustomerSummary.CUSTOMER_SUMMARY);

        set(0, id);
        set(1, name);
        set(2, isActive);
    }

    public CustomerSummaryRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
