/*
 * This file is generated by jOOQ.
*/
package example1.datamodel.tables.records;


import example1.datamodel.tables.CustomerSummary;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerSummaryRecord extends UpdatableRecordImpl<CustomerSummaryRecord> implements Record3<String, String, Boolean> {

    private static final long serialVersionUID = 854381207;

    /**
     * Setter for <code>example1db.customer_summary.id</code>.
     */
    public CustomerSummaryRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>example1db.customer_summary.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>example1db.customer_summary.name</code>.
     */
    public CustomerSummaryRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>example1db.customer_summary.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>example1db.customer_summary.is_active</code>.
     */
    public CustomerSummaryRecord setIsActive(Boolean value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>example1db.customer_summary.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CustomerSummary.CUSTOMER_SUMMARY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CustomerSummary.CUSTOMER_SUMMARY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return CustomerSummary.CUSTOMER_SUMMARY.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerSummaryRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerSummaryRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerSummaryRecord value3(Boolean value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomerSummaryRecord values(String value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerSummaryRecord
     */
    public CustomerSummaryRecord() {
        super(CustomerSummary.CUSTOMER_SUMMARY);
    }

    /**
     * Create a detached, initialised CustomerSummaryRecord
     */
    public CustomerSummaryRecord(String id, String name, Boolean isActive) {
        super(CustomerSummary.CUSTOMER_SUMMARY);

        set(0, id);
        set(1, name);
        set(2, isActive);
    }
}
