/*
 * This file is generated by jOOQ.
*/
package example1.datamodel.tables.records;


import example1.datamodel.tables.UnitsOfWork;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitsOfWorkRecord extends UpdatableRecordImpl<UnitsOfWorkRecord> implements Record9<Long, String, Object, String, Object, String, String, Long, Timestamp> {

    private static final long serialVersionUID = -273882549;

    /**
     * Setter for <code>example1db.units_of_work.uow_seq_number</code>.
     */
    public UnitsOfWorkRecord setUowSeqNumber(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.uow_seq_number</code>.
     */
    public Long getUowSeqNumber() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>example1db.units_of_work.uow_id</code>.
     */
    public UnitsOfWorkRecord setUowId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.uow_id</code>.
     */
    public String getUowId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>example1db.units_of_work.uow_events</code>.
     */
    public UnitsOfWorkRecord setUowEvents(Object value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.uow_events</code>.
     */
    public Object getUowEvents() {
        return (Object) get(2);
    }

    /**
     * Setter for <code>example1db.units_of_work.cmd_id</code>.
     */
    public UnitsOfWorkRecord setCmdId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.cmd_id</code>.
     */
    public String getCmdId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>example1db.units_of_work.cmd_data</code>.
     */
    public UnitsOfWorkRecord setCmdData(Object value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.cmd_data</code>.
     */
    public Object getCmdData() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>example1db.units_of_work.ar_name</code>.
     */
    public UnitsOfWorkRecord setArName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.ar_name</code>.
     */
    public String getArName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>example1db.units_of_work.ar_id</code>.
     */
    public UnitsOfWorkRecord setArId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.ar_id</code>.
     */
    public String getArId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>example1db.units_of_work.version</code>.
     */
    public UnitsOfWorkRecord setVersion(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.version</code>.
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>example1db.units_of_work.inserted_on</code>.
     */
    public UnitsOfWorkRecord setInsertedOn(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>example1db.units_of_work.inserted_on</code>.
     */
    public Timestamp getInsertedOn() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Object, String, Object, String, String, Long, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Object, String, Object, String, String, Long, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UnitsOfWork.UNITS_OF_WORK.UOW_SEQ_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UnitsOfWork.UNITS_OF_WORK.UOW_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field3() {
        return UnitsOfWork.UNITS_OF_WORK.UOW_EVENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UnitsOfWork.UNITS_OF_WORK.CMD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field5() {
        return UnitsOfWork.UNITS_OF_WORK.CMD_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UnitsOfWork.UNITS_OF_WORK.AR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UnitsOfWork.UNITS_OF_WORK.AR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return UnitsOfWork.UNITS_OF_WORK.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return UnitsOfWork.UNITS_OF_WORK.INSERTED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUowSeqNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUowId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value3() {
        return getUowEvents();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCmdId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value5() {
        return getCmdData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getArName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getArId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getInsertedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value1(Long value) {
        setUowSeqNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value2(String value) {
        setUowId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value3(Object value) {
        setUowEvents(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value4(String value) {
        setCmdId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value5(Object value) {
        setCmdData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value6(String value) {
        setArName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value7(String value) {
        setArId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value8(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord value9(Timestamp value) {
        setInsertedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UnitsOfWorkRecord values(Long value1, String value2, Object value3, String value4, Object value5, String value6, String value7, Long value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UnitsOfWorkRecord
     */
    public UnitsOfWorkRecord() {
        super(UnitsOfWork.UNITS_OF_WORK);
    }

    /**
     * Create a detached, initialised UnitsOfWorkRecord
     */
    public UnitsOfWorkRecord(Long uowSeqNumber, String uowId, Object uowEvents, String cmdId, Object cmdData, String arName, String arId, Long version, Timestamp insertedOn) {
        super(UnitsOfWork.UNITS_OF_WORK);

        set(0, uowSeqNumber);
        set(1, uowId);
        set(2, uowEvents);
        set(3, cmdId);
        set(4, cmdData);
        set(5, arName);
        set(6, arId);
        set(7, version);
        set(8, insertedOn);
    }
}
