version: '3.4'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: my-secret-pwd
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  events-projector:
    image: java:alpine
    restart: always
    volumes:
      - ./:/var:z
    command: ["/var/wait-for-port.sh", "db:3306", "--", "java", "-jar", "/var/crabzilla-example1-ha-projector/target/crabzilla-example1-ha-projector.jar"]
    depends_on:
      - db
    env_file:
      - example1.env

  command-handler:
    image: java:alpine
    restart: always
    volumes:
      - ./:/var:z
    command: ["/var/wait-for-port.sh", "db:3306", "--", "java", "-jar", "/var/crabzilla-example1-ha-handler/target/crabzilla-example1-ha-handler.jar"]
    depends_on:
      - db
    env_file:
      - example1.env

  web:
    image: java:alpine
    restart: always
    volumes:
      - ./:/var:z
    command: ["/var/wait-for-port.sh", "db:3306", "--", "java", "-jar", "/var/crabzilla-example1-ha-web/target/crabzilla-example1-ha-web.jar"]
    ports:
      - 8080:8080
    depends_on:
      - db
      - command-handler
    env_file:
      - example1.env

