version: '3.4'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: my-secret-pwd
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  web:
    image: java:alpine
    restart: always
    volumes:
      - ./crabzilla-example1-ha-web/target/crabzilla-example1-ha-web-0.0.6-SNAPSHOT-fat.jar:/var/example1-web-service.jar:z
      - ./wait-for-port.sh:/var/wait-for-port.sh:z
    command: ["/var/wait-for-port.sh", "db:3306", "--", "java", "-jar", "/var/example1-web-service.jar"]
    ports:
      - 8080:8080
    depends_on:
      - db
      - command-handler
    env_file:
      - example1.env

  command-handler:
    image: java:alpine
    restart: always
    volumes:
      - ./crabzilla-example1-ha-handler/target/crabzilla-example1-ha-handler-0.0.6-SNAPSHOT-fat.jar:/var/example1-handler-service.jar:z
      - ./wait-for-port.sh:/var/wait-for-port.sh:z
    command: ["/var/wait-for-port.sh", "db:3306", "--", "java", "-jar", "/var/example1-handler-service.jar"]
    depends_on:
      - db
    env_file:
      - example1.env

  events-projector:
    image: java:alpine
    restart: always
    volumes:
      - ./crabzilla-example1-ha-projector/target/crabzilla-example1-ha-projector-0.0.6-SNAPSHOT-fat.jar:/var/example1-projector-service.jar:z
      - ./wait-for-port.sh:/var/wait-for-port.sh:z
    command: ["/var/wait-for-port.sh", "db:3306", "--", "java", "-jar", "/var/example1-projector-service.jar"]
    depends_on:
      - db
    env_file:
      - example1.env
