version: '3.1'

services:

    db:
        image: mysql:5.6.34
        ports:
               - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pwd
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./crabzilla-example1-ha-web/target/classes/wait-for-it.sh:/var/wait-for-it.sh
#       command: ["./var/wait-for-it.sh", "db:3306", "--", "ls"]

    web:
        image: java:alpine
        volumes:
            - ./crabzilla-example1-ha-web/target/crabzilla-example1-ha-web-0.0.6-SNAPSHOT-fat.jar:/var/app.jar:z
            - ./crabzilla-example1-ha-web/target/classes/conf/:/var/conf
            - ./crabzilla-example1-ha-web/target/classes/wait-for-it.sh:/var/wait-for-it.sh
        command: ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "/var/app.jar", "--conf", "/var/conf/config.properties"]
        ports:
            - 8080:8080
        depends_on:
            - db

    command-handler:
        image: java:alpine
        volumes:
            - ./crabzilla-example1-ha-handler/target/crabzilla-example1-ha-handler-0.0.6-SNAPSHOT-fat.jar:/var/app.jar:z
            - ./crabzilla-example1-ha-handler/target/classes/conf/:/var/conf
            - ./crabzilla-example1-ha-handler/target/classes/wait-for-it.sh:/var/wait-for-it.sh
        command: ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "/var/app.jar", "--conf", "/var/conf/config.properties"]
        depends_on:
            - db

    events-projector:
        image: java:alpine
        volumes:
            - ./crabzilla-example1-ha-projector/target/crabzilla-example1-ha-projector-0.0.6-SNAPSHOT-fat.jar:/var/app.jar:z
            - ./crabzilla-example1-ha-projector/target/classes/conf/:/var/conf
            - ./crabzilla-example1-ha-projector/target/classes/wait-for-it.sh:/var/wait-for-it.sh
        command: ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "/var/app.jar", "--conf", "/var/conf/config.properties"]
        depends_on:
            - db
