/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.jooq.example1.datamodel;


import io.github.crabzilla.jooq.example1.datamodel.tables.CustomerSummary;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customer_summary</code>.
     */
    public static final CustomerSummary CUSTOMER_SUMMARY = CustomerSummary.CUSTOMER_SUMMARY;
}
