/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.jooq.datamodel;


import io.github.crabzilla.jooq.datamodel.tables.Projections;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.projections</code>.
     */
    public static final Projections PROJECTIONS = Projections.PROJECTIONS;
}
