/*
 * This file is generated by jOOQ.
*/
package example1.datamodel.tables;


import example1.datamodel.Example1db;
import example1.datamodel.Keys;
import example1.datamodel.tables.records.EventsProjectionChannelsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsProjectionChannels extends TableImpl<EventsProjectionChannelsRecord> {

    private static final long serialVersionUID = -274114728;

    /**
     * The reference instance of <code>example1db.events_projection_channels</code>
     */
    public static final EventsProjectionChannels EVENTS_PROJECTION_CHANNELS = new EventsProjectionChannels();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventsProjectionChannelsRecord> getRecordType() {
        return EventsProjectionChannelsRecord.class;
    }

    /**
     * The column <code>example1db.events_projection_channels.channel_name</code>.
     */
    public final TableField<EventsProjectionChannelsRecord, String> CHANNEL_NAME = createField("channel_name", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

    /**
     * The column <code>example1db.events_projection_channels.uow_last_seq</code>.
     */
    public final TableField<EventsProjectionChannelsRecord, Long> UOW_LAST_SEQ = createField("uow_last_seq", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>example1db.events_projection_channels</code> table reference
     */
    public EventsProjectionChannels() {
        this("events_projection_channels", null);
    }

    /**
     * Create an aliased <code>example1db.events_projection_channels</code> table reference
     */
    public EventsProjectionChannels(String alias) {
        this(alias, EVENTS_PROJECTION_CHANNELS);
    }

    private EventsProjectionChannels(String alias, Table<EventsProjectionChannelsRecord> aliased) {
        this(alias, aliased, null);
    }

    private EventsProjectionChannels(String alias, Table<EventsProjectionChannelsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Example1db.EXAMPLE1DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EventsProjectionChannelsRecord> getPrimaryKey() {
        return Keys.KEY_EVENTS_PROJECTION_CHANNELS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EventsProjectionChannelsRecord>> getKeys() {
        return Arrays.<UniqueKey<EventsProjectionChannelsRecord>>asList(Keys.KEY_EVENTS_PROJECTION_CHANNELS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsProjectionChannels as(String alias) {
        return new EventsProjectionChannels(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventsProjectionChannels rename(String name) {
        return new EventsProjectionChannels(name, null);
    }
}
