/*
 * This file is generated by jOOQ.
*/
package example1.datamodel.tables.pojos;


import javax.annotation.Generated;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerSummary implements Serializable {

    private static final long serialVersionUID = -653595610;

    private String  id;
    private String  name;
    private Boolean isActive;

    public CustomerSummary() {}

    public CustomerSummary(CustomerSummary value) {
        this.id = value.id;
        this.name = value.name;
        this.isActive = value.isActive;
    }

    public CustomerSummary(
        String  id,
        String  name,
        Boolean isActive
    ) {
        this.id = id;
        this.name = name;
        this.isActive = isActive;
    }

    public String getId() {
        return this.id;
    }

    public CustomerSummary setId(String id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public CustomerSummary setName(String name) {
        this.name = name;
        return this;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public CustomerSummary setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerSummary (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
