/*
 * This file is generated by jOOQ.
*/
package example1.datamodel.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnitsOfWork implements Serializable {

    private static final long serialVersionUID = -85244632;

    private Long      uowSeqNumber;
    private String    uowId;
    private Object    uowEvents;
    private String    cmdId;
    private Object    cmdData;
    private String    arName;
    private String    arId;
    private Long      version;
    private Timestamp insertedOn;

    public UnitsOfWork() {}

    public UnitsOfWork(UnitsOfWork value) {
        this.uowSeqNumber = value.uowSeqNumber;
        this.uowId = value.uowId;
        this.uowEvents = value.uowEvents;
        this.cmdId = value.cmdId;
        this.cmdData = value.cmdData;
        this.arName = value.arName;
        this.arId = value.arId;
        this.version = value.version;
        this.insertedOn = value.insertedOn;
    }

    public UnitsOfWork(
        Long      uowSeqNumber,
        String    uowId,
        Object    uowEvents,
        String    cmdId,
        Object    cmdData,
        String    arName,
        String    arId,
        Long      version,
        Timestamp insertedOn
    ) {
        this.uowSeqNumber = uowSeqNumber;
        this.uowId = uowId;
        this.uowEvents = uowEvents;
        this.cmdId = cmdId;
        this.cmdData = cmdData;
        this.arName = arName;
        this.arId = arId;
        this.version = version;
        this.insertedOn = insertedOn;
    }

    public Long getUowSeqNumber() {
        return this.uowSeqNumber;
    }

    public UnitsOfWork setUowSeqNumber(Long uowSeqNumber) {
        this.uowSeqNumber = uowSeqNumber;
        return this;
    }

    public String getUowId() {
        return this.uowId;
    }

    public UnitsOfWork setUowId(String uowId) {
        this.uowId = uowId;
        return this;
    }

    public Object getUowEvents() {
        return this.uowEvents;
    }

    public UnitsOfWork setUowEvents(Object uowEvents) {
        this.uowEvents = uowEvents;
        return this;
    }

    public String getCmdId() {
        return this.cmdId;
    }

    public UnitsOfWork setCmdId(String cmdId) {
        this.cmdId = cmdId;
        return this;
    }

    public Object getCmdData() {
        return this.cmdData;
    }

    public UnitsOfWork setCmdData(Object cmdData) {
        this.cmdData = cmdData;
        return this;
    }

    public String getArName() {
        return this.arName;
    }

    public UnitsOfWork setArName(String arName) {
        this.arName = arName;
        return this;
    }

    public String getArId() {
        return this.arId;
    }

    public UnitsOfWork setArId(String arId) {
        this.arId = arId;
        return this;
    }

    public Long getVersion() {
        return this.version;
    }

    public UnitsOfWork setVersion(Long version) {
        this.version = version;
        return this;
    }

    public Timestamp getInsertedOn() {
        return this.insertedOn;
    }

    public UnitsOfWork setInsertedOn(Timestamp insertedOn) {
        this.insertedOn = insertedOn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UnitsOfWork (");

        sb.append(uowSeqNumber);
        sb.append(", ").append(uowId);
        sb.append(", ").append(uowEvents);
        sb.append(", ").append(cmdId);
        sb.append(", ").append(cmdData);
        sb.append(", ").append(arName);
        sb.append(", ").append(arId);
        sb.append(", ").append(version);
        sb.append(", ").append(insertedOn);

        sb.append(")");
        return sb.toString();
    }
}
