version: '3.4'

services:

    db:
        image: mysql:5.7
        restart: always
        ports:
               - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pwd
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    web:
        image: java:alpine
        restart: always
        volumes:
            - ./target/crabzilla-example1-monolith-0.0.6-SNAPSHOT-fat.jar:/var/example1-monolith-service.jar:z
            - ./wait-for-port.sh:/var/wait-for-port.sh:z
        command: ["/var/wait-for-port.sh", "db:3306", "--", "java", "-jar", "/var/example1-monolith-service.jar"]
        ports:
            - 8080:8080
        depends_on:
            - db
        env_file:
            - example1.env

