/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.hazelcast.query.datamodel.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.UnexpectedJsonValueType;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IHzProjections extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.hz_projections.entityid</code>.
     */
    public IHzProjections setEntityid(String value);

    /**
     * Getter for <code>public.hz_projections.entityid</code>.
     */
    public String getEntityid();

    /**
     * Setter for <code>public.hz_projections.consumerid</code>.
     */
    public IHzProjections setConsumerid(String value);

    /**
     * Getter for <code>public.hz_projections.consumerid</code>.
     */
    public String getConsumerid();

    /**
     * Setter for <code>public.hz_projections.sequence</code>.
     */
    public IHzProjections setSequence(Long value);

    /**
     * Getter for <code>public.hz_projections.sequence</code>.
     */
    public Long getSequence();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IHzProjections
     */
    public void from(IHzProjections from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IHzProjections
     */
    public <E extends IHzProjections> E into(E into);

    @Override
    public default IHzProjections fromJson(io.vertx.core.json.JsonObject json) {
        try {
            setEntityid(json.getString("entityid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("entityid","java.lang.String",e);
        }
        try {
            setConsumerid(json.getString("consumerid"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("consumerid","java.lang.String",e);
        }
        try {
            setSequence(json.getLong("sequence"));
        } catch (java.lang.ClassCastException e) {
            throw new UnexpectedJsonValueType("sequence","java.lang.Long",e);
        }
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("entityid",getEntityid());
        json.put("consumerid",getConsumerid());
        json.put("sequence",getSequence());
        return json;
    }

}
