/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.jooq.datamodel.tables;


import io.github.crabzilla.jooq.datamodel.Keys;
import io.github.crabzilla.jooq.datamodel.Public;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Projections extends TableImpl<Record> {

    private static final long serialVersionUID = -1253951897;

    /**
     * The reference instance of <code>public.projections</code>
     */
    public static final Projections PROJECTIONS = new Projections();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.projections.name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.projections.last_uow</code>.
     */
    public final TableField<Record, Integer> LAST_UOW = createField(DSL.name("last_uow"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.projections</code> table reference
     */
    public Projections() {
        this(DSL.name("projections"), null);
    }

    /**
     * Create an aliased <code>public.projections</code> table reference
     */
    public Projections(String alias) {
        this(DSL.name(alias), PROJECTIONS);
    }

    /**
     * Create an aliased <code>public.projections</code> table reference
     */
    public Projections(Name alias) {
        this(alias, PROJECTIONS);
    }

    private Projections(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Projections(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Projections(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, PROJECTIONS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PROJECTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.PROJECTIONS_PKEY);
    }

    @Override
    public Projections as(String alias) {
        return new Projections(DSL.name(alias), this);
    }

    @Override
    public Projections as(Name alias) {
        return new Projections(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Projections rename(String name) {
        return new Projections(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Projections rename(Name name) {
        return new Projections(name, null);
    }
}
