/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.pgc.jooq.datamodel;


import io.github.crabzilla.pgc.jooq.datamodel.tables.Projections;

import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> PROJECTIONS_PKEY = UniqueKeys0.PROJECTIONS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> PROJECTIONS_PKEY = Internal.createUniqueKey(Projections.PROJECTIONS, "projections_pkey", new TableField[] { Projections.PROJECTIONS.NAME }, true);
    }
}
