/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.hazelcast.query.datamodel.tables.pojos;


import io.github.crabzilla.hazelcast.query.datamodel.tables.interfaces.IHzProjections;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HzProjections implements VertxPojo, IHzProjections {

    private static final long serialVersionUID = -1621616526;

    private String entityid;
    private String consumerid;
    private Long   sequence;

    public HzProjections() {}

    public HzProjections(IHzProjections value) {
        this.entityid = value.getEntityid();
        this.consumerid = value.getConsumerid();
        this.sequence = value.getSequence();
    }

    public HzProjections(
        String entityid,
        String consumerid,
        Long   sequence
    ) {
        this.entityid = entityid;
        this.consumerid = consumerid;
        this.sequence = sequence;
    }

    @Override
    public String getEntityid() {
        return this.entityid;
    }

    @Override
    public HzProjections setEntityid(String entityid) {
        this.entityid = entityid;
        return this;
    }

    @Override
    public String getConsumerid() {
        return this.consumerid;
    }

    @Override
    public HzProjections setConsumerid(String consumerid) {
        this.consumerid = consumerid;
        return this;
    }

    @Override
    public Long getSequence() {
        return this.sequence;
    }

    @Override
    public HzProjections setSequence(Long sequence) {
        this.sequence = sequence;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HzProjections (");

        sb.append(entityid);
        sb.append(", ").append(consumerid);
        sb.append(", ").append(sequence);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IHzProjections from) {
        setEntityid(from.getEntityid());
        setConsumerid(from.getConsumerid());
        setSequence(from.getSequence());
    }

    @Override
    public <E extends IHzProjections> E into(E into) {
        into.from(this);
        return into;
    }

    public HzProjections(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
