/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.pgc.jooq.example1.datamodel.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerSummary implements Serializable {

    private static final long serialVersionUID = -410276993;

    private Integer id;
    private String  name;
    private Boolean isActive;

    public CustomerSummary() {}

    public CustomerSummary(CustomerSummary value) {
        this.id = value.id;
        this.name = value.name;
        this.isActive = value.isActive;
    }

    public CustomerSummary(
        Integer id,
        String  name,
        Boolean isActive
    ) {
        this.id = id;
        this.name = name;
        this.isActive = isActive;
    }

    public Integer getId() {
        return this.id;
    }

    public CustomerSummary setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public CustomerSummary setName(String name) {
        this.name = name;
        return this;
    }

    public Boolean getIsActive() {
        return this.isActive;
    }

    public CustomerSummary setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerSummary (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
