/*
 * This file is generated by jOOQ.
 */
package io.github.crabzilla.pgc.jooq.example1.datamodel.tables.pojos;


import io.github.crabzilla.pgc.jooq.example1.datamodel.tables.interfaces.ICustomerSummary;
import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerSummary implements VertxPojo, ICustomerSummary {

    private static final long serialVersionUID = 1368415190;

    private Integer id;
    private String  name;
    private Boolean isActive;

    public CustomerSummary() {}

    public CustomerSummary(ICustomerSummary value) {
        this.id = value.getId();
        this.name = value.getName();
        this.isActive = value.getIsActive();
    }

    public CustomerSummary(
        Integer id,
        String  name,
        Boolean isActive
    ) {
        this.id = id;
        this.name = name;
        this.isActive = isActive;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public CustomerSummary setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public CustomerSummary setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public Boolean getIsActive() {
        return this.isActive;
    }

    @Override
    public CustomerSummary setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerSummary (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ICustomerSummary from) {
        setId(from.getId());
        setName(from.getName());
        setIsActive(from.getIsActive());
    }

    @Override
    public <E extends ICustomerSummary> E into(E into) {
        into.from(this);
        return into;
    }

    public CustomerSummary(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
